POST https://ab498.glitch.me/api/auth/register
Content-Type: application/json

{
    "email": "admin",
    "password": "admin"
}

###
https://ab498.glitch.me/getwinstart

###
###
###
###
###
###
###
###
###
###
###
###
###